version: '3'
services:
  ipfs:
    image: ipfs/kubo:latest
    restart: always
    environment:
      IPFS_PROFILE: server
    volumes:
      - ./data/export:/export
      - ./data/data-ipfs:/data/ipfs
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
